import { readFileSync } from "node:fs"
import { resolve } from "node:path"
import { defineConfig } from "vitepress"

const typedocSidebarPath = resolve(__dirname, "../api/typedoc-sidebar.json")
let typedocSidebar: unknown = []
try {
  typedocSidebar = JSON.parse(readFileSync(typedocSidebarPath, "utf-8"))
} catch {
  // Sidebar file is generated by `pnpm api` before build.
}

export default defineConfig({
  title: "Kinem",
  description: "Functional, compositional animation library for TypeScript.",
  lastUpdated: true,
  cleanUrls: true,
  head: [
    ["link", { rel: "icon", type: "image/svg+xml", href: "/favicon.svg" }],
    ["meta", { name: "theme-color", content: "#7c9cff" }],
  ],
  themeConfig: {
    nav: [
      { text: "Guide", link: "/guide/getting-started" },
      { text: "Recipes", link: "/recipes/" },
      { text: "API", link: "/api/" },
      { text: "Migrations", link: "/migrations/gsap" },
      {
        text: "v0.0",
        items: [{ text: "Changelog", link: "https://github.com/joshburgess/kinem/releases" }],
      },
    ],
    sidebar: {
      "/guide/": [
        {
          text: "Introduction",
          items: [
            { text: "Getting started", link: "/guide/getting-started" },
            { text: "Core concepts", link: "/guide/concepts" },
          ],
        },
        {
          text: "Performance",
          items: [{ text: "Renderer modes", link: "/guide/renderer-modes" }],
        },
        {
          text: "Framework adapters",
          items: [
            { text: "React", link: "/guide/react" },
            { text: "Vue", link: "/guide/vue" },
            { text: "Svelte", link: "/guide/svelte" },
            { text: "Solid", link: "/guide/solid" },
          ],
        },
        {
          text: "Tooling",
          items: [{ text: "Devtools", link: "/guide/devtools" }],
        },
      ],
      "/recipes/": [
        {
          text: "Recipes",
          items: [
            { text: "Overview", link: "/recipes/" },
            { text: "Drawer / sheet", link: "/recipes/drawer" },
            { text: "Modal with backdrop", link: "/recipes/modal" },
            { text: "List reorder", link: "/recipes/list-reorder" },
            { text: "Page transitions", link: "/recipes/page-transition" },
            { text: "Scroll-driven hero", link: "/recipes/scroll-hero" },
            { text: "Shared element", link: "/recipes/shared-element" },
          ],
        },
      ],
      "/api/": typedocSidebar as never,
      "/migrations/": [
        {
          text: "Migrations",
          items: [
            { text: "From GSAP", link: "/migrations/gsap" },
            { text: "From Motion One", link: "/migrations/motion" },
            { text: "From Popmotion", link: "/migrations/popmotion" },
          ],
        },
      ],
    },
    socialLinks: [{ icon: "github", link: "https://github.com/joshburgess/kinem" }],
    footer: {
      message: "Released under the MIT License.",
      copyright: "Copyright © Josh Burgess",
    },
    search: { provider: "local" },
    editLink: {
      pattern: "https://github.com/joshburgess/kinem/edit/main/docs/:path",
      text: "Edit this page on GitHub",
    },
  },
})
