import { readFileSync } from "node:fs"
import { resolve } from "node:path"
import { defineConfig } from "vitepress"

const typedocSidebarPath = resolve(__dirname, "../api/typedoc-sidebar.json")
let typedocSidebar: unknown = []
try {
  typedocSidebar = JSON.parse(readFileSync(typedocSidebarPath, "utf-8"))
} catch {
  // Sidebar file is generated by `pnpm api` before build.
}

export default defineConfig({
  title: "Kinem",
  description: "Functional, compositional animation library for TypeScript.",
  lastUpdated: true,
  cleanUrls: true,
  head: [
    ["link", { rel: "icon", type: "image/svg+xml", href: "/favicon.svg" }],
    ["meta", { name: "theme-color", content: "#7c9cff" }],
  ],
  themeConfig: {
    nav: [
      { text: "Guide", link: "/guide/getting-started" },
      { text: "API", link: "/api/" },
      { text: "Migrations", link: "/migrations/gsap" },
      {
        text: "v0.0",
        items: [
          { text: "Changelog", link: "https://github.com/joshburgess/motif/releases" },
        ],
      },
    ],
    sidebar: {
      "/guide/": [
        {
          text: "Introduction",
          items: [
            { text: "Getting started", link: "/guide/getting-started" },
            { text: "Core concepts", link: "/guide/concepts" },
          ],
        },
      ],
      "/api/": typedocSidebar as never,
      "/migrations/": [
        {
          text: "Migrations",
          items: [
            { text: "From GSAP", link: "/migrations/gsap" },
            { text: "From Motion One", link: "/migrations/motion" },
          ],
        },
      ],
    },
    socialLinks: [{ icon: "github", link: "https://github.com/joshburgess/motif" }],
    footer: {
      message: "Released under the MIT License.",
      copyright: "Copyright © Josh Burgess",
    },
    search: { provider: "local" },
    editLink: {
      pattern: "https://github.com/joshburgess/motif/edit/main/docs/:path",
      text: "Edit this page on GitHub",
    },
  },
})
